### ISSUE TITLE
Alarm tagging fails due to unsupported character in resource name

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-guardian#94]
Stack trace

```
WARN: throttled max times (3) tagging alarm EndpointTimeTaken, skipping ...
/usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Aws::CloudWatch::Errors::InvalidParameterValue (Aws::CloudWatch::Errors::InvalidParameterValue)
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
    from /usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/seahorse/client/request.rb:72:in `send_request'
    from /usr/local/bundle/gems/aws-sdk-cloudwatch-1.67.0/lib/aws-sdk-cloudwatch/client.rb:3720:in `tag_resource'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian/tagger.rb:30:in `tag_alarm'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian.rb:244:in `block (2 levels) in tag_alarms'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian.rb:242:in `each'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian.rb:242:in `block in tag_alarms'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian.rb:226:in `each'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/lib/cfnguardian.rb:226:in `tag_alarms'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    from /usr/local/bundle/gems/cfn-guardian-0.9.1/exe/cfn-guardian:4:in `<top (required)>'
    from /usr/local/bundle/bin/cfn-guardian:23:in `load'
    from /usr/local/bundle/bin/cfn-guardian:23:in `<main>'
[Container] 2023/01/12 01:30:17 Command did not exit successfully cfn-guardian tag-alarms --config $CONFIG_YAMLS --region us-east-1 exit status 1
[Container] 2023/01/12 01:30:17 Phase complete: BUILD State: FAILED
[Container] 2023/01/12 01:30:17 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cfn-guardian tag-alarms --config $CONFIG_YAMLS --region us-east-1. Reason: exit status 1
```

**Comment by Guslington** [comment]
need further detail with `--debug` flag

**Comment by Guslington** [comment]
looks to be as a result of a unsupported character in the tag value. some https endpoints include query parameters with a `?` which is unsupported

```
Allowed characters are letters, numbers, spaces representable in UTF-8, and the following characters: . : + = @ _ / - (hyphen).
```

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Tagging.html#tagging-restrictions

**Comment by tarunmenon95** [comment]
Just handle error and pass on tagging
